development:
  clients:
    default:
      database: miniConektaDB_dev
      hosts:
        - localhost:27017
      options:
  options:

test:
  clients:
    default:
      database: miniConektaDB_dev
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
